### ISSUE TITLE
Sign-In Failure when Installing App with other Machines

### ISSUE THREAD

**Issue by bscotty** [pajato/GameChat#21]
When Installing the newest version of the app, containing the sign-in screen, there is a major problem in that sign-in's functionality is flawless when done on the primary machine where the code was written, but when installed on another computer, sign-in fails. Here is the pertinent logcat:

`D/GCInstanceIDService: GameChat chat token: {cxH1P6szWjA:APA91bHQixds_kIUq4If7_U7gBgFm1aR7xhi_d_9f7Gij3sHZ37-UdWet8P8TvojcbHBnjYdxB8fKUXHtMmteMHM8mJgAhGXWZM77OTW8E1NuY12fJ62gLnSClo9AsJV7OxKTJHHCd4j}.`
`V/FA: onActivityCreated`
`V/FA: Activity resumed, time: 209517104`
`V/FA: Activity paused, time: 209517108`
`D/FirebaseInstanceId: topic sync succeeded`
`E/SignInActivity: Google Sign In failed.`
`W/System.err: java.lang.Throwable: stack dump`
`W/System.err:     at java.lang.Thread.dumpStack(Thread.java:490)`
`W/System.err:     at com.pajato.android.gamechat.signin.SignInActivity.onActivityResult(SignInActivity.java:79)`
`W/System.err:     at android.app.Activity.dispatchActivityResult(Activity.java:6456)`
`W/System.err:     at android.app.ActivityThread.deliverResults(ActivityThread.java:3695)`
`W/System.err:     at android.app.ActivityThread.handleSendResult(ActivityThread.java:3742)`
`W/System.err:     at android.app.ActivityThread.-wrap16(ActivityThread.java)`
`W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1393)`
`W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)`
`W/System.err:     at android.os.Looper.loop(Looper.java:148)`
`W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5417)`
`W/System.err:     at java.lang.reflect.Method.invoke(Native Method)`
`W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)`
`W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)`
`V/FA: Activity resumed, time: 209519753`
`V/FA: Inactivity, disconnecting from AppMeasurementService`
`E/DynamiteModule: Failed to load module descriptor class: Didn't find class "com.google.android.gms.dynamite.descriptors.com.google.firebase.auth.ModuleDescriptor" on path: DexPathList[[zip file "/data/app/com.pajato.android.gamechat-1/base.apk"],nativeLibraryDirectories=[/data/app/com.pajato.android.gamechat-1/lib/arm64, /vendor/lib64, /system/lib64]]`
`V/FA: Session started, time: 209527619`
`I/FA: Tag Manager is not found and thus will not be used`
`D/FA: Logging event (FE): _s, Bundle[{_o=auto}]`
`V/FA: Using measurement service`
`V/FA: Connecting to remote service`
`D/FA: Connected to remote service`
`V/FA: Processing queued up service tasks: 1`
`E/DataBuffer: Internal data leak within a DataBuffer object detected!  Be sure to explicitly call release() on all DataBuffer extending objects when you are done with them. (internal object: com.google.android.gms.common.data.DataHolder@ba627f4)`
`V/FA: Inactivity, disconnecting from AppMeasurementService`

**Comment by bscotty** [comment]
Resolved. The issue was not adding my SHA-1 key to the firebase console, which has since been done.
